import { Task } from "./types";

export const DEFAULT_ROUTINE_TASKS: Task[] = [
  // Morning
  {
    id: "morning-cook-breakfast",
    title: "Cook breakfast",
    timeBlock: "morning",
    recurrence: "daily",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
  {
    id: "morning-clean-office-guest",
    title: "Clean the office and guest room, take trash out / change plastic",
    timeBlock: "morning",
    recurrence: "daily",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
  {
    id: "morning-walis-labas",
    title: "Mag-walis sa labas",
    timeBlock: "morning",
    recurrence: "daily",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
  {
    id: "morning-linis-baba",
    title: "Mag-linis sa baba",
    timeBlock: "morning",
    recurrence: "daily",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
  {
    id: "morning-play-tali",
    title: "Play with Tali",
    timeBlock: "morning",
    recurrence: "daily",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
  {
    id: "morning-feed-tali",
    title: "Feed Tali (during breakfast)",
    timeBlock: "morning",
    recurrence: "daily",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
  {
    id: "morning-clean-togo-bathroom",
    title: "Clean Togo's bathroom",
    timeBlock: "morning",
    recurrence: "daily",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
  {
    id: "morning-clean-common-bathroom",
    title: "Clean common bathroom sa baba",
    timeBlock: "morning",
    recurrence: "daily",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },

  // After Breakfast
  {
    id: "ab-wash-dishes",
    title: "Wash dishes",
    timeBlock: "after-breakfast",
    recurrence: "daily",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
  {
    id: "ab-clean-bedroom-masters",
    title: "Clean the bedroom (masters)",
    timeBlock: "after-breakfast",
    recurrence: "daily",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
  {
    id: "ab-change-trash-plastic",
    title: "Change the trash plastic",
    timeBlock: "after-breakfast",
    recurrence: "daily",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
  {
    id: "ab-scrub-master-bathroom",
    title: "Scrub & clean master bathroom (shower & toilet)",
    timeBlock: "after-breakfast",
    recurrence: "every-other-day",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
  {
    id: "ab-change-bedsheets",
    title: "Change bedsheets",
    timeBlock: "after-breakfast",
    recurrence: "bimonthly",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
  {
    id: "ab-prepare-lunch",
    title: "Prepare lunch",
    timeBlock: "after-breakfast",
    recurrence: "daily",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
  // Pet Tank Schedule
  {
    id: "ab-clean-small-betta-tanks",
    title: "Clean small betta tanks (lego tanks)",
    timeBlock: "after-breakfast",
    recurrence: "monday,thursday",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
  {
    id: "ab-clean-turtle-tanks",
    title: "Clean turtle tanks",
    timeBlock: "after-breakfast",
    recurrence: "wednesday,sunday",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
  {
    id: "ab-clean-big-betta-tanks",
    title: "Clean big betta tanks",
    timeBlock: "after-breakfast",
    recurrence: "tuesday,saturday",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
  {
    id: "ab-clean-big-fish-tanks",
    title: "Clean big fish tanks",
    timeBlock: "after-breakfast",
    recurrence: "sunday",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },

  // After Lunch
  {
    id: "al-pababain-tali",
    title: "Pabababain si Tali para umihi",
    timeBlock: "after-lunch",
    recurrence: "daily",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
  {
    id: "al-iakyat-tali",
    title: "Iakyat si Tali",
    timeBlock: "after-lunch",
    recurrence: "daily",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
  {
    id: "al-mag-akyat-kape",
    title: "3 PM - Mag-akyat ng kape/merienda",
    timeBlock: "after-lunch",
    recurrence: "daily",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
  {
    id: "al-wash-dishes",
    title: "Wash dishes",
    timeBlock: "after-lunch",
    recurrence: "daily",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
  {
    id: "al-prepare-dinner",
    title: "Prepare dinner",
    timeBlock: "after-lunch",
    recurrence: "daily",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },

  // After Dinner
  {
    id: "ad-wash-dishes",
    title: "Wash dishes",
    timeBlock: "after-dinner",
    recurrence: "daily",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
  {
    id: "ad-prepare-dogs-food",
    title: "Prepare dogs' food (Tiki, Tali, Togo)",
    timeBlock: "after-dinner",
    recurrence: "daily",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
  {
    id: "ad-feed-tiki",
    title: "Feed Tiki",
    timeBlock: "after-dinner",
    recurrence: "daily",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
  {
    id: "ad-pababain-tali",
    title: "Pabababain si Tali",
    timeBlock: "after-dinner",
    recurrence: "daily",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
  {
    id: "ad-linis-baba",
    title: "Linis sa baba",
    timeBlock: "after-dinner",
    recurrence: "daily",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
  {
    id: "ad-scrub-garage",
    title: "Scrub garage with soap and Zonrox, water the plants",
    timeBlock: "after-dinner",
    recurrence: "wednesday",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },

  // Anytime
  {
    id: "any-wash-tumblers",
    title: "Wash and change water sa tumblers",
    timeBlock: "anytime",
    recurrence: "daily",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
  {
    id: "any-clean-ref",
    title: "Clean the ref",
    timeBlock: "anytime",
    recurrence: "saturday",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
  {
    id: "any-take-out-trash",
    title: "Take out the trash",
    timeBlock: "anytime",
    recurrence: "sunday",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
  {
    id: "any-sort-laundry",
    title: "Sort laundry",
    timeBlock: "anytime",
    recurrence: "tuesday",
    isRoutine: true,
    completed: false,
    completedAt: null,
  },
];
